version: '3.9'

services: 
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile_backend
    ports:
      - 9696:9696
    networks:
      - api

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile_frontend
    ports:
      - 8501:8501
    networks:
      - api

networks:
  api:
    driver: bridge

