FROM python:3.11.6-slim

EXPOSE 8000

RUN apt-get update &&\
    pip install pipenv

WORKDIR /app

COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pipenv install --system --deploy

COPY ["backend_fastapi.py", "model_C=1.0.bin", "./"]

ENTRYPOINT ["uvicorn", "backend_fastapi:app", "--reload"]