FROM python:3.11.6-slim

EXPOSE 8501

WORKDIR /app

COPY ["Pipfile", "Pipfile.lock", "frontend.py", "./"]

RUN apt-get update && \
    pip install pipenv && \
    apt-get install -y build-essential && \
    pipenv install --system --deploy

ENTRYPOINT ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]